### ISSUE TITLE
Nested groups and chains raise ChordCounter.DoesNotExist

### ISSUE THREAD

**Issue by JannKleen** [celery/django-celery-results#194] opened 2021-04-09 13:52 UTC
I get this error with `django-celery-results==2.0.1` and `Celery==5.0.5`. I didn't test the `dev` branches yet.
Similar to #177 the following Exception is raised, but in this case it seems to happen because of the nesting of groups and chains.

Exception:
```
django_celery_results.models.ChordCounter.DoesNotExist: ChordCounter matching query does not exist.
```

This fails:
```
            transaction.on_commit(
                 chain(
                     task_1,
                     group(
                         task_2,
                         chain(
                             task_3,
                             group(task_4, task_5)),
                     ),
                     task_6,
                 ).delay
            )
```

This works:
```
            transaction.on_commit(
                chain(
                    task_1,
                    group(
                        task_2,
                        task_3,
                    ),
                    group(task_4, task_5),
                    task_6,
                ).delay
            )
```

**Comment by auvipy** [comment] 2021-04-11 03:40
this should be fixed in master. https://github.com/celery/django-celery-results/commit/3f74b825fc1d7af6d5dccc9a9ff583abfb0aa0ab i will release soon

**Comment by thedrow** [comment] 2021-04-11 09:01
@auvipy Second beta?

**Comment by AllexVeldman** [comment] 2021-04-16 06:43
3f74b82 will not raise the error but if there is a bug in nested chords it might be that a callback won't be executed.
@JannKleen do you know at the end of which task the exception is raised?

I'll do some testing to see if I can recreate this and if all tasks are executed correctly.

**Comment by AllexVeldman** [comment] 2021-04-16 07:30
@auvipy my suspicion was right, this is the result when run with the master branch:
```shell
[2021-04-16 07:08:00,893] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_1[4d356049-60c2-4014-9c70-81cfb2bee88a]  
[2021-04-16 07:08:00,912] [ForkPoolWorker-1] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 1
[2021-04-16 07:08:00,939] [ForkPoolWorker-1] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_1[4d356049-60c2-4014-9c70-81cfb2bee88a] succeeded in 0.042876192999999674s: None
[2021-04-16 07:08:00,948] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_2[0c712ed2-a6eb-4905-8b41-55fc38d0bac2]  
[2021-04-16 07:08:06,071] [ForkPoolWorker-2] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 2
[2021-04-16 07:08:06,085] [ForkPoolWorker-2] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_2[0c712ed2-a6eb-4905-8b41-55fc38d0bac2] succeeded in 0.04307537600000089s: None
[2021-04-16 07:08:06,973] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_3[14125c56-6853-414b-896d-cf2bc3f8184f]  
[2021-04-16 07:08:06,994] [ForkPoolWorker-2] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 3
[2021-04-16 07:08:07,034] [ForkPoolWorker-2] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_3[14125c56-6853-414b-896d-cf2bc3f8184f] succeeded in 0.056360951999998576s: None
[2021-04-16 07:08:07,142] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_4[d0b9f6ff-81c3-484b-9257-26ee523f42a9]  
[2021-04-16 07:08:07,299] [ForkPoolWorker-3] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 4
[2021-04-16 07:08:07,321] [ForkPoolWorker-3] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_4[d0b9f6ff-81c3-484b-9257-26ee523f42a9] succeeded in 0.05146732000000043s: None
[2021-04-16 07:08:08,536] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_5[0735d763-a08d-4f0c-b445-9032a510db1b]  
[2021-04-16 07:08:08,558] [ForkPoolWorker-3] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 5
[2021-04-16 07:08:08,567] [ForkPoolWorker-3] [WARNING] [django_celery_results.backends.database] Can't find ChordCounter for Group 2b7b2eba-f843-4422-85e5-908bf262b951
[2021-04-16 07:08:08,569] [ForkPoolWorker-3] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_5[0735d763-a08d-4f0c-b445-9032a510db1b] succeeded in 0.028897945000000647s: None
```

With some additional logs for sequences:
```shell
[2021-04-16 07:24:17,021] [ForkPoolWorker-1] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 1
[2021-04-16 07:24:17,024] [ForkPoolWorker-1] [INFO] [django_celery_results.backends.database] on_chord_part_return - Group 1ba4acec-1a21-493a-ad38-85b23af68acf

[2021-04-16 07:24:17,485] [ForkPoolWorker-2] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 2
[2021-04-16 07:24:17,493] [ForkPoolWorker-2] [INFO] [django_celery_results.backends.database] on_chord_part_return - Group 1ba4acec-1a21-493a-ad38-85b23af68acf

[2021-04-16 07:24:18,076] [ForkPoolWorker-2] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 3

[2021-04-16 07:24:18,531] [ForkPoolWorker-3] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 4
[2021-04-16 07:24:18,539] [ForkPoolWorker-3] [INFO] [django_celery_results.backends.database] on_chord_part_return - Group 1ba4acec-1a21-493a-ad38-85b23af68acf
[2021-04-16 07:24:18,547] [ForkPoolWorker-3] [INFO] [django_celery_results.backends.database] Trigger Callback, Delete Group 1ba4acec-1a21-493a-ad38-85b23af68acf
[2021-04-16 07:24:18,561] [ForkPoolWorker-3] [INFO] [django_celery_results.backends.database] Group not ready - Group 1ba4acec-1a21-493a-ad38-85b23af68acf

[2021-04-16 07:24:20,092] [ForkPoolWorker-3] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 5
[2021-04-16 07:24:20,100] [ForkPoolWorker-3] [INFO] [django_celery_results.backends.database] on_chord_part_return - Group 1ba4acec-1a21-493a-ad38-85b23af68acf
[2021-04-16 07:24:21,727] [ForkPoolWorker-3] [WARNING] [django_celery_results.backends.database] Can't find ChordCounter for Group 1ba4acec-1a21-493a-ad38-85b23af68acf
```

So the issue is in the original length of the top-level group, it's being triggered after task_4 instead of task_5.
I'll see if the Redis backend handles this case correctly

**Comment by AllexVeldman** [comment] 2021-04-16 07:39
Redis log:
```shell
[2021-04-16 07:38:39,708] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_1[eef2f666-d477-4da0-996e-2016b3d9471e]  
[2021-04-16 07:38:39,717] [ForkPoolWorker-1] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 1
[2021-04-16 07:38:39,720] [ForkPoolWorker-1] [INFO] [celery.canvas] apply_chord - Group a11da2d8-ee1a-4a2d-bf7b-b86e9912fd33
[2021-04-16 07:38:39,757] [ForkPoolWorker-1] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_1[eef2f666-d477-4da0-996e-2016b3d9471e] succeeded in 0.044746176000000304s: None
[2021-04-16 07:38:39,868] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_2[65bd0346-92a9-435d-8ca3-4101c3936a02]  
[2021-04-16 07:38:40,144] [ForkPoolWorker-2] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 2
[2021-04-16 07:38:40,148] [ForkPoolWorker-2] [INFO] [celery.backends.base] on_chord_part_return - Group a11da2d8-ee1a-4a2d-bf7b-b86e9912fd33
[2021-04-16 07:38:40,151] [ForkPoolWorker-2] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_2[65bd0346-92a9-435d-8ca3-4101c3936a02] succeeded in 0.020867630999999776s: None
[2021-04-16 07:38:40,571] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_3[0ba9b40b-f34e-405e-9d62-8f5905fafdf6]  
[2021-04-16 07:38:40,582] [ForkPoolWorker-2] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 3
[2021-04-16 07:38:40,638] [ForkPoolWorker-2] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_3[0ba9b40b-f34e-405e-9d62-8f5905fafdf6] succeeded in 0.06057350299999875s: None
[2021-04-16 07:38:40,745] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_4[012ae855-14f9-4774-ada1-bef1cd94c86a]  
[2021-04-16 07:38:41,012] [ForkPoolWorker-3] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 4
[2021-04-16 07:38:41,016] [ForkPoolWorker-3] [INFO] [celery.backends.base] on_chord_part_return - Group a11da2d8-ee1a-4a2d-bf7b-b86e9912fd33
[2021-04-16 07:38:41,019] [ForkPoolWorker-3] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_4[012ae855-14f9-4774-ada1-bef1cd94c86a] succeeded in 0.02017579199999986s: None
[2021-04-16 07:38:41,677] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_5[de530510-892d-444e-bc6c-ac99914f944c]  
[2021-04-16 07:38:41,686] [ForkPoolWorker-3] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 5
[2021-04-16 07:38:41,690] [ForkPoolWorker-3] [INFO] [celery.backends.base] on_chord_part_return - Group a11da2d8-ee1a-4a2d-bf7b-b86e9912fd33
[2021-04-16 07:38:42,256] [ForkPoolWorker-3] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_5[de530510-892d-444e-bc6c-ac99914f944c] succeeded in 0.5735485610000026s: None
[2021-04-16 07:38:42,367] [MainProcess] [INFO] [celery.worker.strategy] Received task: chainstock.taskqueue.chordcounter_tasks.task_6[152f7054-13f7-42e1-853a-12f3b99a017a]  
[2021-04-16 07:38:42,641] [ForkPoolWorker-4] [INFO] [chainstock.taskqueue.chordcounter_tasks] Task 6
[2021-04-16 07:38:42,642] [ForkPoolWorker-4] [INFO] [chainstock.taskqueue.chordcounter_tasks] ([None, [None, None]],)
[2021-04-16 07:38:42,646] [ForkPoolWorker-4] [INFO] [celery.app.trace] Task chainstock.taskqueue.chordcounter_tasks.task_6[152f7054-13f7-42e1-853a-12f3b99a017a] succeeded in 0.018303156999998293s: None
```

**Comment by AllexVeldman** [comment] 2021-04-16 08:08
This was fixed in the redis backend with https://github.com/celery/celery/pull/6354
I'll see if I can extract the useful parts.


Possibly related for the future: https://github.com/celery/celery/pull/6576
This seems to have broken the same thing for celery master:
https://github.com/celery/celery/issues/6721

It also introduced a `set_chord_size` we might need to implement to not break the generator type behaviour.

**Comment by auvipy** [comment] 2021-04-16 08:53
Allex can you dedicate some time to contribute upstream to celery

**Comment by AllexVeldman** [comment] 2021-04-16 09:03
@auvipy I don't have a huge amount of time available, let me see what I can dedicate.

This issue of calculating chord size does seem a more general issue spanning multiple backends.
What exactly would you like me to look into?

**Comment by AllexVeldman** [comment] 2021-04-16 09:05
> This was fixed in the redis backend with [celery/celery#6354](https://github.com/celery/celery/pull/6354)
> I'll see if I can extract the useful parts.

The Redis implementation relies on `GroupResult.save()/.restore()` so without https://github.com/celery/django-celery-results/issues/40 I won't be able to replicate it here.

**Comment by AllexVeldman** [comment] 2021-04-16 10:02
Actually, I might have just overlooked something in the original implementation.
The chord size is available on  the Signature `body["chord_size"]` in `apply_chord()`

My serialisation of the GroupResult is already sufficient for triggering the callback.

@auvipy how can I add a test like [this](https://github.com/maybe-sybr/celery/blob/842293760250d983893bddafe023e018f2d1d50a/t/integration/test_canvas.py#L443) to this project? I did not find tests that actually delay tasks for this project.

**Closed** 2021-04-16 11:22 UTC

**Comment by JannKleen** [comment] 2022-01-31 16:43
@auvipy We finally got around to upgrading to the latest version, but we're still running into this issue.

Our current pipeline looks like this.
```python
            transaction.on_commit(
                 group(
                     task_0,
                     chain(
                         task_1,
                         group(
                             task_2,
                             chain(
                                 task_3,
                                 task_4, 
                                 task_5,
                                 task_6,
                             ),
                         ),
                         task_7,
                     ),
                 ).delay
            )
```

With the added complexity of `task_2` calling `self.replace` to replace itself with a group of n (normally 2-8) tasks.
I'm not quite sure how to debug this, but if you want me to test anything, just tell me what you'd like to see.

**Comment by AllexVeldman** [comment] 2022-02-02 15:35
@JannKleen odd, I've tried to reproduce the setup you mention but was not able to get an error or miss any tasks:
https://github.com/AllexVeldman/django-celery-results/runs/5038842196?check_suite_focus=true

it's setup so you can run the same locally using docker-compose for reproducibility.

I also tried making the replacement tasks for `task_2` take longer to see if it was a race-condition somewhere in the ChordCounter but that only resulted in having to wait longer for `task_7` to trigger.

Would it be possible for to check https://github.com/AllexVeldman/django-celery-results/pull/1  and see if the task setup is the same as what you expect?
