### ISSUE TITLE
ChordCounter DoesNotExist

### ISSUE THREAD

**Issue by Ixiodor** [celery/django-celery-results#177] opened 2020-11-29 13:00 UTC
I get this error for each task i launch:
```
Traceback (most recent call last):
  File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 476, in trace_task
    mark_as_done(
  File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 156, in mark_as_done
    self.on_chord_part_return(request, state, result)
  File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 112, in on_chord_part_return
    ChordCounter.objects.select_for_update()
  File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django_celery_results.models.ChordCounter.DoesNotExist: ChordCounter matching query does not exist.
```
Reinstalling all seems to fix for a while, after start that again.
Celery 5.0.2 and 2.0.0 django_results

**Comment by Ixiodor** [comment] 2020-11-30 10:27
Chords should be writte on DB but that seems to not happen

**Comment by ngrj93** [comment] 2021-01-16 11:01
> Chords should be writte on DB but that seems to not happen

Were you able to figure out the issue?

**Comment by auvipy** [comment] 2021-01-16 13:05
raise self.model.DoesNotExist(
django_celery_results.models.ChordCounter.DoesNotExist: ChordCounter matching query does not exist

did you check your database that all the models are there?

**Comment by auvipy** [comment] 2021-01-20 19:00
closing as it doesn't seem to be an issue with this package. prove me wrong, please

**Comment by Rjevski** [comment] 2021-01-27 08:11
If you have chords that were started using the previous (<2.0) release of the results backend, you shut down the worker before those chords complete, starting a worker with the new (>=2.0) results backend will spit out these errors with undefined behavior on task execution (I'm not sure if the chord restarts entirely or just gets abandoned with half the tasks missing). To test back and forth easily you can create 2 virtualenvs, one with the old version and one with the new version - have 2 terminals open (with their respective virtualenvs) and you can quickly switch between the 2 workers. The old version seems to handle the DB migration just fine so you can test back and forth without having to downgrade the DB.

Steps to reproduce:

* Create a Django project with Celery configured to use the Django results backend.
* Write some tasks that use chords, these dummy tasks for example:

```
from time import sleep

from celery import chord

from queue_test.celery import app


@app.task
def inner_completion_callback(*args, **kwargs):
    print(f'Inner completion callback')

    sleep(10)


@app.task
def completion_callback(*args, **kwargs):
    print(f'Completion callback')

    sleep(10)


@app.task
def further_downstream_task(pk):
    print(f'Downstream task for pk {pk}')
    sleep(1)


@app.task
def do_something(pk):
    signatures = [further_downstream_task.s(pk) for _ in range(10)]

    print(f'Downstream chord for pk {pk}')

    chord(signatures)(inner_completion_callback.s(pk=pk))

    sleep(1)


@app.task
def make_chord(pk):
    signatures = [do_something.s(pk) for _ in range(10)]

    print(f'Started new {len(signatures)}-task chord for pk {pk}')

    chord(signatures)(completion_callback.s(pk=pk))
```

* Start a worker using the *old* version of the results backend (it seems like the version of the results backend used by the worker is all that matters - the version used by the web app doesn't have an impact).
* Submit the main `make_chord` task however you wish (`./manage.py shell`, Django admin action, etc).
* While the worker is in the middle of processing the tasks (a few seconds after submitting the task) shut down the worker with Ctrl+C.
* Upgrade the package to =>2.0, migrate the DB, restart the worker - it should start printing out those exceptions as it tries to process chords started by the old version.

This only happens when chords have been _started_ by the old version's workers and then picked up by the new version. If you wait for all the task to finish (or purge the queue) before upgrading you're fine, but this might be undesirable in production (as you'd also need to prevent _new_ tasks from being submitted while waiting for the old ones to complete).

Has an upgrade path been considered when developing this `ChordCounter` feature? Or is the above the expected upgrade path (although as I said before, it might not be suitable in all scenarios).

**Comment by auvipy** [comment] 2021-01-27 09:15
@arnau126 did you face it?

**Comment by arnau126** [comment] 2021-01-27 09:50
I don't use chords in my project.
"chord syncronisation" is a new feature of 2.0.0 added by @AllexVeldman  in #144 . He may know why already started chords by the old version crash when `django-celery-results` is updated.

However, I think the problem is:
The "chord syncronisation" feature depends on a ChordCounter instance which the old version does not create.
Then, when `django-celery-results` is upgraded, the backend looks for this not-existing-instance and it crashes with this error:

> django_celery_results.models.ChordCounter.DoesNotExist: ChordCounter matching query does not exist.

Don't know if it is a bug, or just an acceptable breaking change since 2.0.0 was a major release.

**Comment by AllexVeldman** [comment] 2021-01-27 09:59
@arnau126 You are right, the ChordCounter object is created in `apply_chord` (https://github.com/celery/django-celery-results/blob/961177e50b468b470c2d830d16d92760e3dff9a6/django_celery_results/backends/database.py#L119)

So when the chord was started before the update, this object does not exist and would break the existing Chord.

**Comment by AllexVeldman** [comment] 2021-01-27 10:14
@Rjevski I did not consider this upgrade path.
The previous chord synchronisation relied on a polling task `celery.chord_unlock` which would retry until the chord was done. @Rjevski is that task still triggering after the update?

If that is the case the a backwards-compatible option would be to catch and ignore `ChordCounter.DoesNotExist` in `on_chord_part_return` which would have the side-effect of not failing a successful task because it could not find the Chord.

@arnau126 would this be an acceptable patch?

**Comment by Rjevski** [comment] 2021-01-27 22:10
> Is that task still triggering after the update?

How would I check given the repro steps above? I can upload my entire test repo if this helps. You'll need Postgres and Redis running to test it.

**Comment by AllexVeldman** [comment] 2021-01-28 07:34
> How would I check given the repro steps above? I can upload my entire test repo if this helps. You'll need Postgres and Redis running to test it.

You can monitor the tasks created using [Flower](https://flower.readthedocs.io/en/latest/) or similar and look for `celery.chord_unlock`, this task should retry every `result_chord_retry_interval` seconds (default 1) until all tasks in the header of a Chord have finished. (https://github.com/celery/celery/blob/29eda054555fa95c83210e5e6bc3e839c80bcd3b/celery/app/builtins.py#L73)

So using the steps you provided, after updating to django_celery_results > 2.0.0, this task should still be retrying.

Then if you would delay `make_chord` again after the update that task should no longer appear.

**Closed** 2021-02-05 19:13 UTC
Labels: bug
