### ISSUE TITLE
Unknown System Variable 'tx_isolation' when using MySQL 8

### ISSUE THREAD

**Issue by Planswalker** [celery/django-celery-results#83] opened 2018-12-17 19:36 UTC
Hello,

I recently have created a set of celery tasks using django_celery_results on a Mysql 8 backend. Most of the time this works well, but recently I've seen the following error while waiting for celery tasks to complete:

`_mysql_exceptions.OperationalError: (1193, "Unknown system variable 'tx_isolation'")`

When tracing the error I was able to locate the following in managers.py:

```   
 def warn_if_repeatable_read(self):
        if 'mysql' in self.current_engine().lower():
            cursor = self.connection_for_read().cursor()
            if cursor.execute('SELECT @@tx_isolation'):
                isolation = cursor.fetchone()[0]
                if isolation == 'REPEATABLE-READ':
                    warnings.warn(TxIsolationWarning(W_ISOLATION_REP.strip()))
```

Which I am pretty sure is the cause of this issue - `tx_isolation` was deprecated in MySQL 5.7 ([see here](https://dev.mysql.com/doc/refman/5.7/en/added-deprecated-removed.html#optvars-deprecated)) and MySQL 8 changed the name of the system variable from `tx_isolation` to `transaction_isolation` ([see here](https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html#mysql-nutshell-removals))

Thanks!

**Comment by liquidpele** [comment] 2019-05-06 03:42
Fix was merged, closing this.   Please re-open if the issue persists.

**Comment by ndido98** [comment] 2019-05-29 11:10
The PR responsible for fixing this issue has introduced a regression in MariaDB (I use 10.3.15, but I suppose this is valid for versions newer than 10.1), where the `transaction_isolation` variable doesn't exist and it's still named the old MySQL way, so `tx_isolation`.

Django itself had the same issue and the same regression, which [was fixed in this commit.](https://github.com/django/django/commit/e3c852cbd609484b272f563f3c21066fb12ef7f8).

**Comment by liquidpele** [comment] 2019-05-29 11:21
@Planswalker or @ndido98 could one of you make a PR with a similar fix that will handle both?

**Comment by liquidpele** [comment] 2019-05-30 20:08
Closing this since a PR was merged to fix the fix.

**Closed by liquidpele** 2019-05-30 20:08 UTC
Labels: bug
